### ISSUE TITLE
Cannot build on CircleCi. Vapor 3. Swift 5.1.

### ISSUE THREAD

**Issue by ernichechelski** [pvzig/SlackKit#192]
Hi. I'm sure that this is an issue with SlackKit because I easily manage to build with success my project without using this dependency :) 

I'm using following job in `config.yml` in `.circleci` catalog. Classic configuration.

```
  build_unit_test:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install libssl-dev pkg-config
      - run:
          name: Compile code
          command: swift build --disable-sandbox --verbose
      - run:
          name: Run unit tests
          command: swift test
```
Logs below: 
[circlecifaillogs.txt](https://github.com/pvzig/SlackKit/files/5567296/circlecifaillogs.txt)

I'm using Swift 5.1 with Vapor 3. 
```
// swift-tools-version:5.1
import PackageDescription

let package = Package(
  name: "myproject",
  products: [
    .library(name: "myproject", targets: ["App"])
  ],
  dependencies: [
    // 👤 Authentication and Authorization framework for Fluent.
    .package(url: "https://github.com/vapor/auth.git", from: "2.0.0"),
    // 🔵 Swift ORM (queries, models, relations, etc) built on PostgreSQL.
    .package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0"),
    // Support for templates.
    .package(url: "https://github.com/vapor/leaf.git", from: "3.0.0"),
    // 💧 A server-side Swift web framework.
    .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
    // Framework for managing social authenticaions.
    .package(url: "https://github.com/vapor-community/Imperial.git", from: "0.7.1"),
    // Allow using .env files in Vapor 3.
    .package(url: "https://github.com/vapor-community/vapor-ext.git", from: "0.1.0"),
    // Used for sending slack messages.
    .package(url: "https://github.com/pvzig/SlackKit.git", .upToNextMinor(from: "4.6.0")),
    // Used for running jobs.
    .package(url: "https://github.com/vapor/jobs.git", from: "0.2.7"),
    // Redis driver for jobs.
    .package(url: "https://github.com/vapor/jobs-redis-driver", from: "0.2.7"),
    // Vapor simple file logger.
    .package(url: "https://github.com/hallee/vapor-simple-file-logger.git", from: "1.0.1"),

  ],
  targets: [
    .target(name: "App", dependencies: ["Authentication", "FluentPostgreSQL", "Jobs", "JobsRedisDriver", "Leaf", "SlackKit", "Imperial", "SimpleFileLogger", "Vapor", "VaporExt"]),
    .target(name: "Run", dependencies: ["App"]),
    .testTarget(name: "AppTests", dependencies: ["App"])
  ]
)
```
Commenting out SlackKit resolves the issue, however, I cannot manage to figure out how to fix this correctly.

CircleCi environment: 
```
Build-agent version 1.0.45693-f637b996 (2020-11-17T15:18:22+0000)
Docker Engine Version: 18.09.6
Kernel Version: Linux 6d04732c58d3 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 Linux
Starting container swift:5.1
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading swift:5.1
5.1: Pulling from library/swift 
```
Thanks for your time to check this issue 😄
